name: data_processor
description: A standalone Dart script for processing Firebase data.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_core: ^3.1.1
  firebase_database: ^11.0.1

# We need to specify the path to the main flutter app's firebase_options.dart
# This is a bit of a workaround, but it's the easiest way to share the config.
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
